# Generated by Django 5.0.4 on 2024-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokermon_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
