version: '3.7'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./pokedex.sql:/docker-entrypoint-initdb.d/pokedex.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
